---
title: "Figures Code - from Fox, Honeycutt, and Jussim 2018"
author: "Nick_Fox"
date: "2/1/2018"
output: html_document
---

```{r setup, include=FALSE}
#load packages
library(dplyr)
library(ggplot2)
```

This figure shows the average social network size of those who identify as QRP users and the general population of psychologists.
```{r echo = FALSE}

#load in network size data
networks <- read.csv("network_sizes.csv", header = TRUE)

#figure comparing general and QRP user network size.  Visualizes what delta estimates.
networks %>% 
  ggplot(aes(x = network_size, colour = population)) + geom_density(size = 1) + scale_x_continuous(breaks=seq(0,2200,150))



```

This figure shows the three estimates we generates: The Unmatched Count Technique (UCT) Estimate, the Direct Estimate, and the Generalized Network Scale-Up (GNSUM) Estimate
```{r echo = FALSE}
#reads in the data (that I consolidated from the 4 bootstrapping files)
estimates <- read.csv("qrp_estimates.csv", header = TRUE)

#turns the data into factors for graphing
estimates$estimate_type <- factor(estimates$estimate_type, levels = c("unmatched_count", "direct_estimate", "GNSUM"))

#creates figure
estimates %>% 
  ggplot(aes(x = estimate_type, y = mean)) + geom_point(size = 2, aes(color = estimate_type)) + coord_flip() + geom_errorbar(aes(ymin = lower, ymax = upper, width = 0, color = estimate_type)) + xlab("") + ylab("Estimated Prevalence of QRP Use (%)") + ylim(-22,60) + theme_classic() + theme(legend.position = "none") + geom_hline(yintercept=0, linetype = "dotted") + scale_x_discrete(labels = c("UCT Estimate", "Direct Estimate", "GNSUM Estimate")) + scale_color_manual(values=c("grey50", "black", "black"))

#saves the figure as a png file (remove hashtag to save - it's hashed now for knitting purposes)
#ggsave("estimate_hold.png")


```

